[package]
name = "scrt_sss"
version = "0.1.0"
edition = "2021"

[lib]
name = "scrt_sss"
path = "src/lib.rs"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ec_curve = {path = "../ec_curve"}

serde = { version = "1.0.152", features = ["derive"] }
rand_core = { version = "0.6.4", default-features = false }

[dev-dependencies]
rstest = "0.13.0"
serde_json = "1.0.48"
bincode2 = "2.0.1"
rand = "0.8.5"